

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    
    
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: